

const appsList = [
    {
        appName: "無料のワードクラウドアプリ｜Pythonで画像作成",
        icon: "bi bi-cloud-fog",
        linkTo: "/blog-cloud",
        color: "orange",
        description: "WordCloudライブラリを使って、あなたの記事で多用されているワードを抜き出します。ワード数トップ10ランキング付き。",
        searchq: "blog image ai 画像 wordcloud",
        id: "blogcloud",
    },
    // {
    //     appName: "Twitterのトレンドを取得",
    //     icon: "bi bi-twitter",
    //     linkTo: "/get-trends",
    //     color: "#1d9bf0",
    //     description: "Twitterのトレンドを一覧にします。ワンクリックで地域別にトレンド一覧が出てきます。リンクをクリックすれば、Tweet一覧へ。",
    //     searchq: "twitter trends ツイッター トレンド",
    // },
    {
        appName: "QRコード作成",
        icon: "bi bi-qr-code",
        linkTo: "/qrmaker",
        color: "black",
        description: "どんな文字列（日本語以外）でもQRコードにできます。その場で画像を表示するので好きなだけお作りください。",
        searchq: "qr code QRコード QR作成",
        id: "qr",

    },
    {
        appName: "【簡単アプリ】西暦を和暦変換｜昭和・平成を西暦へ",
        icon: "bi bi-arrow-left-right",
        linkTo: "/yearConverter",
        color: "#ff91bb",
        description: "西暦と和暦を変換します。昭和や平成、令和と西暦間を一発で変換できるアプリです。ローマ字と数字だけで変換できるのでとても簡単。",
        searchq: "西暦 和暦 変換 年 年号 year converter",
        id: "yearconverter",
    },
    {
        appName: "ランダム文字列の生成",
        icon: "bi bi-shuffle",
        linkTo: "/get-random-string",
        color: "#af74d4",
        description: "ランダムな文字列を生成します。100文字以内ならいくらでも。パスワードやHPのスラッグにお使いください。",
        searchq: "ランダム random 文字 パスワード 生成",
        id: "randomstring",
    },
    {
        appName: "ワードカウンター",
        icon: "bi bi-fonts",
        linkTo: "/wordcounter",
        color: "#b3ffff",
        description: "フォームにテキストを貼り付ければ、文字数をカウントしてくれます。Twitterやブログ記事など何でもお使いください。",
        searchq: "ワード テキスト 文字 文字数 カウント word text string count length",
        id: "wordcounter",
    },
    {
        appName: "【無料】ハッシュ化ツール｜hmac SHA256",
        icon: "bi bi-hash",
        linkTo: "/hashapp",
        color: "#ff886c",
        description: "無料でハッシュ化できるツールをお探しですか？Pythonのhmacライブラリを使って、お好きな文字をハッシュ化します。",
        searchq: "hash hmac sha256 ハッシュ 文字 暗号 シークレット",
        id: "hashapp",
    },
    {
        appName: "プライバシーポリシーテンプレート自動生成アプリ",
        icon: "bi bi-journal-text",
        linkTo: "/privacy-policy-maker",
        color: "#8a8a8a",
        description: "プライバシーポリシーのテンプレートをお探しですか？ドメイン名を入力すれば、簡単にあなた専用のプライバシーポリシーの雛形が作れるアプリです。",
        searchq: "privacy plicy プライバシーポリシー 自動生成 テンプレート",
        id: "privacypolicymaker",
    },
    {
        appName: "バイト数カウントツール",
        icon: "bi bi-chat-square-text-fill",
        linkTo: "/byte-counter",
        color: "#004c7a",
        description: "フォームに文字列を入力するだけで、バイトに変換しその大きさを表示します。",
        searchq: "バイト ビット byte bit size",
        id: "bytecounter",
    },
    {
        appName: "JSON Formatter",
        icon: "bi bi-code-square",
        linkTo: "/json-prettier",
        color: "#ffa9a9",
        description: "JSON文字列を綺麗な形式に整えます。JSON Formatter/JSON Beautifier",
        searchq: "json pretty prettier format フォーマット indent インデント",
        id: "jsonprettier",
    },
    {
        appName: "ポモドーロ・タイマー",
        icon: "bi bi-clock-fill",
        linkTo: "/pomodoro-timer",
        color: "#b3ffff",
        description: "ポモドーロ・タイマーで作業効率UP。25分-5分のインターバルで集中力を高めましょう。",
        searchq: "timer pomodoro タイマー ポモドーロ 作業 work",
        id: "pomodorotimer",
    },
]

export default appsList