name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_API_URI: ${{ secrets.VITE_API_URI }}
          VITE_TOKEN: ${{ secrets.VITE_TOKEN }}
          VITE_HMAC_SECRET: ${{ secrets.VITE_HMAC_SECRET }}
          VITE_TOOLS_TOKEN: ${{ secrets.VITE_TOOLS_TOKEN }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
